
###
POST http://localhost:8080/company
Content-Type: application/json

{
  "corpName":"General Uzoqova",
  "directorName":"15",
  "address":"15"
}


###
PUT http://localhost:8080/company/{{id}}

###
DELETE http://localhost:8080/company/{{id}}

###
GET http://localhost:8080/company

###
GET http://localhost:8080/company/{{id}}